## Configuration file for DWGettingStarted application.
---
# User login.
login: javaeeeee
# User  password.
password: crimson

#Server configuration.
server:
    applicationConnectors:
        - type: http
          port: 8080
        - type: https
          port: 8443
          keyStorePath: dwstart.keystore
          keyStorePassword: crimson
          validateCerts: false

# Database settings.
database:
    # the name of the JDBC driver, mysql in our case
    driverClass: com.mysql.jdbc.Driver
    # the username
    user: javaeeeee
    # the password
    password: 1
    # the JDBC URL; the database is called DWGettingStarted
    url: jdbc:mysql://localhost:3306/DWGettingStarted